### ISSUE TITLE
Preview is always random. Random doc option can be removed

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#124]
In the preview window you can select a "random doc" or not. If not, it takes the first document of a collection. Since lexicons are unsorted, this is also random (especially in live environments). So this "random doc" option can be removed, because even if you turn "random doc" off you get the first of the collection which has also random behaviour.

**Comment by sashamitrovich** [comment]
"Random" doc is a setting that says: "pick a random document from the collection". If "Random" document is not used, same document will be used in Preview over and over (which is the fn.head() document in the collection and is, indeed, "random" since there's no guarantee about the order of docs saved in the db).

**Comment by sashamitrovich** [comment]
Not using "Random" is a useful feature since it gives you the possibility to run Preview always on the same document and observe how the changes in the graph are affecting the resulting document, for the same source. I personally, use this often.

**Comment by sashamitrovich** [comment]
Improved the tool-tip information for the Random documents.
