### ISSUE TITLE
Rationalize block/library names

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#144]
The block/library names is getting messy. The lower/uppercase for naming is different, and also the libraries are not very clear. Clean this up, and come up with a clear hierarchy. We can provide a migration tool to migrate existing graphs ones issue #143 is in.

**Comment by danielholgate** [comment]
There will be several activities within this ticket:

Analyse current menu structure and block names/functions
Remove duplicate/obsolete/unneeded blocks (based on group/user feedback)
Design new menu structure
Potential new block names
Examine how block definitions are loaded/stored with goal to simplifying(currently some in Litegraph vs core.json etc)

**Comment by sashamitrovich** [comment]
Testing now. Some remarks:

- The old "constant" has to go away ( we have a new, more flexible one) 👎 
- Array was missed in the conversion (New mapping for basic/Array is Merge/Array) 👎 
- _lowercase_ block doesn’t exist anymore - it’s OK that I have to change it manually 🆗 
- same for _const_ (number) 🆗 
- map values was recognized in one instance but not in the other (can't explain it):
<img width="283" alt="Screenshot 2020-04-22 at 08 46 39" src="https://user-images.githubusercontent.com/15609655/79949610-19ad0c00-8476-11ea-949e-10e24cb398ce.png">


- Anything within subgraph seems to be completely broken 👎 
- I'm not sure about the Mapping group - maybe that group shouldn't exist (conflict with DHF mapping) and, instead, move all the blocks to Filter. Rationale: map values (and ranges) and select case do a kind of filtering of the values - something comes in and something else (or partially the same plus something else) comes out...
- remove "New mapping for basic/const is Generate/constNumber" 👎

**Comment by sashamitrovich** [comment]
- Array is fixed (conversion works) 🆗 
- Const (number) is removed 🆗 

Outstanding issues:
- String templating migrated for 1 block only, other same blocks ignored 👎 
I assume it's because it's called "Generate/String Template" and not "Generate/Templating"
- Map values migrated for 1 block only, other same blocks ignored 👎 
- Envelope converted for 1 block only, other same (Envelope) blocks ignored 👎 

Good sample graph to play with: https://github.com/marklogic-community/pipes/blob/master/Examples/Customer360/Customer360-demo-graph-01.1_.json

In general, it seems there's a pattern where only 1 block of a type gets migrated and the others are ignored.

**Comment by danielholgate** [comment]
Additional note: There is now a "String Case" block which replaces both the Uppercase and Lowercase blocks. At the moment these are not auto-replaced however, users need to manually replace them as a one-off operation

**Comment by sashamitrovich** [comment]
All outstanding issues fixed. Closing.
