### ISSUE TITLE
selectCase is having the same problems as lookup

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#147]
selectCase is having the same problems as lookup last week:

1.  If you change the nr of inputs, the lines drop off. So if you change 3 to 4, then the lines from input 1-3 drops off and you need to redraw. 
2.  Most likely in execution mode, only the default hardcoded nr of inputs will work, even if you set in the editor nr of inputs 10. This refers to #122  for the Lookup block 
3. The lines are not correctly draw upon graph load. Reproduction: add a selectCase with 10 inputs. Assign 10 constant to those inputs. Save the graph, load again.

**Comment by danielholgate** [comment]
For issue 1 Fixed adding/removing of connections 
For issue 2 Now adding 20 outputs. Should be enough for any situation
Can't replicate #3 - reloading worked for me in Beta 4 (connections not lost)

Note: "Default" input is the now the second input in the list instead of being the last. This makes is much easier for the dynamic adding/removing

**Comment by danielholgate** [comment]
Note: "Default" input is the now the second input in the list instead of being the last. This makes is much easier for the dynamic adding/removing

**Comment by danielholgate** [comment]
This is fixed I believe and we can close if @josvanroosmalen agrees
