### ISSUE TITLE
As a user, I want to provide my own user block library (json and sjs) at middle tier startup

### ISSUE THREAD

**Issue by epoilvet** [marklogic-community/pipes#17]

**Comment by sashamitrovich** [comment]
OK, can you provide a little bit more details how it's supposed to work?
Using a parameter?

**Comment by epoilvet** [comment]
There are 2 files that can be customised by user himself:
front : /statics/library/user.json
and back : /src/main/ml-modules/root/custom-modules/pipes/user.sjs
The user must be able to provide replacement files for these 2. Could be in the params or in the Gradle ?

**Comment by sashamitrovich** [comment]
Sure, it's doable both ways. If we want to allow this to be possible in runtime, there are 2 things that have to be done:
- when booting, Pipes has to consider this new location for user.sjs and push it instead of the "standard" user.sjs (or perhaps we don't push/include the "standard" user.sjs at all, since it has no value? This would simplify the implementation)
- when serving static files, Pipes should provide the new user.json instead of the "standard" one (here same question - do we need the "standard" one since it makes this ticket more complicated?)

**Comment by sashamitrovich** [comment]
Note to myself, probably good resource: https://stackoverflow.com/questions/49490079/spring-boot-mvc-how-to-serve-static-files-outside-jar-with-special-characters

https://www.baeldung.com/spring-mvc-static-resources

**Comment by sashamitrovich** [comment]
TO-DO: document it.

**Comment by sashamitrovich** [comment]
Documented: https://github.com/marklogic-community/pipes/wiki/4.-Creating-custom-user-blocks-for-developers
