### ISSUE TITLE
Reloaded blocks not available in graph

### ISSUE THREAD

**Issue by danielholgate** [marklogic-community/pipes#24]
When a block is reloaded from the database the details appear in the "Source Blocks" panel but the block does not appear in the Library (right click) within the graph

**Comment by epoilvet** [comment]
Actually this was the expected behaviour in the concept. The idea was to reload a configuration, change it eventually, before creating the block.
Not sure what is best: if it's inserted by default in the library, it means it might have to be overridden  (with side effects on existing inserted versions)

**Comment by danielholgate** [comment]
Good question then. Perhaps saving blocks to the database never makes sense? User creates one, immediately (or at least within that session) adds it to the Graph.  The graphs themselves get saved and loaded, and all their blocks come with them. 
That being the case, perhaps saving the blocks themselves isn't needed?

**Comment by danielholgate** [comment]
Implemented reload and insert into graph. Still need to add the check/ warning for reload of blocks with the same name as existing blocks in a graph

**Comment by sashamitrovich** [comment]
@danielholgate , would you like to create a new issue for the check / warning or still do that under this one?

**Comment by sashamitrovich** [comment]
Warning enhancement moved to #63.
