### ISSUE TITLE
subgraph output is inconsistent and cannot be used as input to other blocks

### ISSUE THREAD

**Issue by kghmanuel** [marklogic-community/pipes#242]
A subgraph defined as the following:

![image](https://user-images.githubusercontent.com/421770/82006352-2c43eb00-969a-11ea-93dc-5d6231bcbe6c.png)

ends up becoming a repeated value when connected to an envelope
[sample.zip](https://github.com/marklogic-community/pipes/files/4631981/sample.zip)

flattenArray ends up with an error message of:
![image](https://user-images.githubusercontent.com/421770/82006431-5d242000-969a-11ea-958b-b081fa20721b.png)

while using fn.head() does not change the result.

**Comment by epoilvet** [comment]
Subgraph is primary designed to loop the array or sequence provided in the first input of the subgraph block. The issue you see is because the subgraph was iterating the chars of the scalar (string) provided as input.
In 1.1 branch the subgraph block is not longer iterating on input if not an array or seq but will process it as is.
