### ISSUE TITLE
Gradle plugin for deploy/undeploy pipes backend

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#38]
A Gradle plugin is needed to deploy/redeploy/undeploy pipes backend. This is needed for automated production environments and CICD pipelines.

**Comment by sashamitrovich** [comment]
OK, this should no be hard to do - all we need is apply a pattern to LoadModulesCommand and DeleteModulesCommand.

Perhaps @rjrudin can advise how to do that?

**Comment by rjrudin** [comment]
mlModulesRegex works for mlLoadModules - it's a property you set on AppConfig.

**Comment by sashamitrovich** [comment]
Right now, the jar will copy to the DHF project & deploy the backend modules (will deploy only Pipes backend modules).

Subsequent calls to mlLoadModules or mlReloadModules would pick up also Pipes modules since they're now in the DHF project.

@josvanroosmalen, can you describe a bit closer what you need, please? Thanks.

**Comment by sashamitrovich** [comment]
Could use https://github.com/marklogic-community/ml-gradle/wiki/Bundles for this.

**Comment by sashamitrovich** [comment]
Done. @josvanroosmalen, I've updated the README to explain how to use the bundle. Please test on your side. Thanks.
