### ISSUE TITLE
Write a High Performance Execution Engine

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#40]
I can work on a high performance Execution Engine. I have some background in compiler/language design, so I can help with this ;-). 

I first will play around with Pipes for the coming week for a POC, and we first need to collaborate on ideas/requirements. 

I think the best way is to write a SJS code generator, which converts the model in native SJS code. An alternative is converting the model to an Intermediate Code which then requires an interpreter on top of SJS, which cost extra development work and does not add anything because SJS is already portable etc. 

I see that execution of the code is relatively isolated, so the code generator generated code should have the same input/output to make it a (relatively easy) drop-in-replacement.

**Comment by epoilvet** [comment]
Here are some ideas :
- I agree, generating native code should be the target because it will provide the best perf and eventually allow advanced users/devs to "hack the code" if needed.
- Generated code in any case is not used to reload Pipes, serialized graph should still be the reference to save/load graph
- move to mjs as the perf gap is supposed to be important
- Litegraph can provide the order of the block to be executed. It should be possible to use it to generate static calls to get applicable inputs, execute block logic and set outputs.
- Subgraph could eventually be processed by spawned functions (as they loop on input array/sequence)
- It should be possible to log individual block state (inputs, outputs) during the execution in order to feed the Pipes UI for debugging. The objective would be, if requested by the preview function, to return all the states of the blocks in case the execution succeed and/or failed
- In addition, could be interesting for debugging and optimisation to know where the execution time is spent, so if debug mode log execution time of each individual block

**Comment by sashamitrovich** [comment]
First implementation written, follow-up issues created.
